version: '4'
services:
  mongodb: 
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local

